version: '3.7'

services:

  drupal:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-drupal"
    image: "${DRUPAL_IMAGE}"
    environment:
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}" # Site URI for Drush 9
    volumes:
      - .:/app:delegated
      - ssh:/tmp/amazeeio_ssh-agent:ro
    networks:
      - internal
      - dev-network
    labels:
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: "Host:${DRUPAL_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https

  mariadb:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: mysql:5.7
    #volumes:
    #  - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - 3306
    networks:
      - internal

networks:
  internal:
    external: false
  dev-network:
    name: stonehenge-network
    external: true

volumes:
  ssh:
    name: stonehenge-ssh
    external: true
