---
- name: Enable remi repo for MySQL.
  set_fact: mysql_enablerepo="remi"
  when: mysql_enablerepo is not defined or mysql_enablerepo == ""

- name: Enable remi repo for PHP 7.2
  set_fact: php_enablerepo="remi,remi-php72"
  when: php_version == "7.2"

- name: Enable remi repo for PHP 7.3
  set_fact: php_enablerepo="remi,remi-php73"
  when: php_version == "7.3"

- name: Do yum update to avoid yum-cron conflicts
  yum: name=yum state=latest

- name: Create nginx group, avoiding startup problems
  group:
    name: nginx
    state: present

- name: Create nginx user, avoiding startup problems
  user:
    name: nginx
    group: nginx
    state: present
