---
- hosts: all
  vars:
    deploy_folder: "deploy"
    repo: "git@github.com:UniversityofHelsinki/ResearchDataServiceChannel.git"
    backups_path: "{{ projects.default.root }}/backups"

  tasks:

    - name: "Get code from Github ({{ git_branch }} branch)"
      local_action:
        module: git
        repo: "{{ repo }}"
        dest: "../{{ deploy_folder }}"
        version: "{{ git_branch }}"
        force: yes
        depth: 1

    - name: "Build code for {{ project_env }} environment"
      local_action: "command docker run --rm -v {{ lookup('env', 'PWD') }}/{{ deploy_folder }}:/app --user=druid druidfi/drupal:7.3 composer install --no-dev --ignore-platform-reqs"

    - name: "Create release artifact for {{ project_env }} environment"
      local_action: "command tar -hczf artifact.tar.gz --files-from=conf/artifact/include --exclude-from=conf/artifact/exclude"
      args:
        chdir: "../{{ deploy_folder }}"

    - name: Gather facts about remote
      setup:

    - name: Get timestamp for the release
      set_fact: timestamp="{{ ansible_date_time.epoch }}"

    - name: Create database backup
      shell: "/usr/local/bin/drush -r {{ projects.default.public_root }} sql-dump > {{ backups_path }}/{{ timestamp }}.sql"
      become: yes

    - block:

        - name: Make sure releases folder exists
          file:
            path: "{{ projects.default.root }}/releases/{{ timestamp }}"
            state: directory
            mode: 0755

        - name: "Extract artifact into {{ projects.default.root }}/releases/{{ timestamp }}"
          unarchive:
            src: "../{{ deploy_folder }}/artifact.tar.gz"
            dest: "{{ projects.default.root }}/releases/{{ timestamp }}"
            group: root
            owner: root

        - name: Set symlinks
          file:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
          with_items:
            - { src: "{{ projects.default.root }}/releases/{{ timestamp }}", dest: "{{ projects.default.current }}" }
            - { src: "{{ projects.default.root }}/shared/files", dest: "{{ projects.default.public_root }}/sites/default/files" }

        - name: Copy local.settings.php and saml.local.php
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            remote_src: yes
          with_items:
            - { src: "{{ projects.default.root }}/shared/local.settings.php", dest: "{{ projects.default.public_root }}/sites/default/local.settings.php" }
            - { src: "{{ projects.default.root }}/shared/saml.local.php", dest: "{{ projects.default.public_root }}/sites/default/saml.local.php" }

      become: yes

    - name: Run drush commands
      shell: drush -y -r {{ projects.default.public_root }} {{ item }}
      with_items:
        - "updb -y" # Performs database updates.
        - "cim -y"  # Imports configuration changes.
        - "cr"      # Clears caches.

    - name: Cleanup (keep 10 latest releases)
      shell: ls -dt releases/*/ | tail -n +11 | xargs rm -rf
      args:
        chdir: "{{ projects.default.root }}"
      become: yes
