---
- hosts: all
  become: yes
  pre_tasks:
    - include_vars: "RedHat.yml"
      tags: [ always ]
    - import_tasks: tasks/init-redhat.yml
      tags: [ always ]
  tasks:
    - name: Install extra packages
      package: name="{{ item }}" state=installed
      with_items: "{{extra_packages | list}}"
  roles:
    - { role: geerlingguy.repo-remi,      tags: [ 'repo' ] }
    - { role: geerlingguy.repo-epel,      tags: [ 'repo' ] }
    - { role: geerlingguy.git,            tags: [ 'git' ] }
    - { role: geerlingguy.mysql,          tags: [ 'mysql' ] }
    - { role: geerlingguy.php-versions,   tags: [ 'php' ] }
    - { role: geerlingguy.php,            tags: [ 'php' ] }
    - { role: geerlingguy.php-mysql,      tags: [ 'php' ] }
    - { role: geerlingguy.php-pecl,       tags: [ 'php' ] }
    - { role: geerlingguy.composer,       tags: [ 'composer' ] }
    - { role: geerlingguy.drush,          tags: [ 'drush' ] }
    - { role: jdauphant.nginx,            tags: [ 'nginx' ] }
    - { role: jdauphant.ssl-certs,        tags: [ 'ssl' ] }
    - { role: geerlingguy.certbot,        tags: [ 'ssl' ] }
